Publish metadata receipt as JSON to rabbit
ONSdigital/census-rm-pubsub pull request #21
Opened 2019-05-09 13:25 UTC by jcox-dev

## Motivation and Context

The new [Case Processor](https://github.com/ONSdigital/census-rm-case-processor) has decreed "Death to XML!" so instead of using an XML message template, we now can publish the required details of a receipted eQ as JSON instead.

## What has changed

- JSON message made up of the pubsub notification's metadata + `response_datetime`
- Updated tests

## How to test?

`make test`

NB: the Case Processor does not yet subscribe to the `Case.Responses` queue.

2019-05-13 15:18 UTC, nealedj approved these changes

2019-05-13 15:18 UTC, nealedj commented on test/component/test_component.py
> +        expected_msg = json.dumps({'case_id': expected_case_id,
For the benefit of your future selves might it be worth adding questionnaire_id in here as well? Then it's clear where that value is expected to appear.

2019-05-14 14:39 UTC, liamtoozer approved these changes
👍

2019-05-15 12:50 UTC, LukeLoze1 requested changes

2019-05-15 12:50 UTC, LukeLoze1 commented on docker-compose.yml
> +    image: eu.gcr.io/census-ci/rm/census-rm-pubsub:latest
should this be  eu.gcr.io/census-rm-ci/rm/census-rm-pubsub:latest

2019-05-17 09:12 UTC, LukeLoze1 approved these changes

2019-05-21 08:07 UTC, merged