Break the rabbit URL into its component variables
ONSdigital/census-rm-pubsub pull request #22
Opened 2019-05-13 15:15 UTC by nealedj

## Motivation and Context
Currently the only way to set the RabbitMQ connection variables is via the compond URL parameters. This isn't ideal for when we'll want to be able to pull in the username and password from Kubernetes secrets.

## What has changed
Breaks out the Rabbit URL into its component parameters. 

## How to test?
`make test`

2019-05-14 06:49 UTC, jcox-dev requested changes
Unexpected param comment in one of the helper functions - otherwise looks useful!

NB. these changes will impact at least the following:
- [environment variables in docker-dev](https://github.com/ONSdigital/census-rm-docker-dev)
- [k8s deployments](https://github.com/ONSdigital/census-rm-kubernetes)

2019-05-14 06:49 UTC, jcox-dev commented on app/rabbit_helper.py
> +    :param parameters: The CollectionParameters for the connection
`parameters` doesn't exist in `init_rabbitmq` parameter list?

2019-05-14 06:49 UTC, jcox-dev commented on app/rabbit_helper.py
> +    return pika.BlockingConnection(parameters)
👍

2019-05-15 13:01 UTC, nealedj commented
Can be merged once https://github.com/ONSdigital/census-rm-kubernetes/pull/45 and https://github.com/ONSdigital/census-rm-docker-dev are merged.

2019-05-17 08:56 UTC, jcox-dev approved these changes

2019-05-21 07:06 UTC, davidmort approved these changes

2019-05-28 09:02 UTC, merged