Unit tests
ONSdigital/census-rm-pubsub pull request #8
Opened 2019-02-15 13:57 UTC by LukeLoze1

## Motivation and Context
unit testing for rabbit_helper and subscriber

## What has changed
Unit tests added for them

## How to test?
pipenv install
pipenv shell
pytest test/

## Links
https://trello.com/b/E9lArxTH/ras-rm-orange

2019-02-18 12:47 UTC, rjweeks requested changes

2019-02-18 12:47 UTC, rjweeks commented on test/test_rabbit_helper.py
> +            channel_mock.queue_bind(exchange=RM_RABBIT_EXCHANGE, queue=RM_RABBIT_QUEUE, routing_key=RM_BINDING_KEY)
Needs .assert_called_once_with

2019-02-18 13:09 UTC, rjweeks submitted a review, later dismissed

2019-02-18 13:09 UTC, rjweeks commented on test/test_rabbit_helper.py
> +
Fix PEP8 warnings.

2019-02-19 09:06 UTC, AdamHawtin requested changes
Tests seem good, though to run in PyCharm you do have to make sure the working directory is set to the project directory or the `subscriber` can't find its message templates.

Also, the README could use some direction on running the unit tests. Perhaps a Makefile would be useful like we've used in the other python projects just to collect together the various shell commands into simple targets like `make test`.

2019-02-19 09:06 UTC, AdamHawtin commented on test/helpers/when_then_return.py
> +    return when_then_return
These two functions can be combined if you make `expected_kwargs` a kwarg itself with default of an empty dictionary and check both the expected args and kwargs. Also something like `create_stub_function` might be a clearer name, it took me a little while to realise exactly what the purpose of these was.

2019-02-19 09:35 UTC, jcox-dev commented on test/helpers/when_then_return.py
> +    return when_then_return
@AdamHawtin Solid suggestions. I've refactored and updated the README in the [latest commit](https://github.com/ONSdigital/census-rm-pubsub/pull/8/commits/e7381f7153d16f155077c432dac5d393ecda6b72).

2019-02-19 09:52 UTC, AdamHawtin approved these changes

2019-02-19 10:11 UTC, merged